@OrganizadorCampeonato_HostAddress = http://localhost:5133/api/jugadores

GET {{OrganizadorCampeonato_HostAddress}}
Accept: application/json
Content-Type: application/json

###

POST {{OrganizadorCampeonato_HostAddress}}
Accept: application/json
Content-Type: application/json

{
  "identificacion": "1112223334420",
  "nombres": "Juagador 2e",
  "apellidos": "Apellido 2e",
  "genero": 0,
  "fechaNaciemiento": "2000-06-10T14:00:00",
  "telefono": "22224444"
}