@OrganizadorCampeonato_HostAddress = http://localhost:5133/api/personas

GET {{OrganizadorCampeonato_HostAddress}}?PageNumber=1&Nombres=2
Accept: application/json

###

GET {{OrganizadorCampeonato_HostAddress}}/01992283-fb9c-77f6-b92a-6919208bd857
Accept: application/json

###

POST {{OrganizadorCampeonato_HostAddress}}
Accept: application/json
Content-Type: application/json

{
  "identificacion": "1112223334442",
  "nombres": "Fernando",
  "apellidos": "Mux",
  "genero": 0,
  "fechaNacimiento": "2000-06-01T14:00:00",
  "telefono": "22224444"
}

###

PUT {{OrganizadorCampeonato_HostAddress}}/01992283-fb9c-77f6-b92a-6919208bd857
Accept: application/json
Content-Type: application/json

{
  "identificacion": "1112223334445",
  "nombres": "Jugador Nombre",
  "apellidos": "Jugador Apellido",
  "genero": 0,
  "fechaNaciemiento": "0001-01-01T00:00:00",
  "telefono": "55553333"
}