// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrganizadorCampeonato.Persistencia;

#nullable disable

namespace OrganizadorCampeonato.Persistencia.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260616032616_AddSegundoTiempoExcedido")]
    partial class AddSegundoTiempoExcedido
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.Arbitro", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UltimaFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("UltimaModificacionPor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Arbitros");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimaFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("UltimaModificacionPor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.Entrenador", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UltimaFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("UltimaModificacionPor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Entrenadores");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.Equipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EntrenadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UltimaFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("UltimaModificacionPor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EntrenadorId");

                    b.HasIndex("Nombre");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.EquipoJugador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaIncorporacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JugadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UltimaFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("UltimaModificacionPor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId");

                    b.HasIndex("EquipoId", "JugadorId")
                        .IsUnique();

                    b.ToTable("EquipoJugadores");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.Jugador", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UltimaFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("UltimaModificacionPor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.Partido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GanadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Grupo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("PuntosLocal_P1")
                        .HasPrecision(5)
                        .HasColumnType("decimal(5,0)");

                    b.Property<decimal?>("PuntosLocal_P2")
                        .HasPrecision(5)
                        .HasColumnType("decimal(5,0)");

                    b.Property<decimal?>("PuntosLocal_P3")
                        .HasPrecision(5)
                        .HasColumnType("decimal(5,0)");

                    b.Property<decimal?>("PuntosLocal_P4")
                        .HasPrecision(5)
                        .HasColumnType("decimal(5,0)");

                    b.Property<decimal?>("PuntosLocal_Prorroga")
                        .HasPrecision(5)
                        .HasColumnType("decimal(5,0)");

                    b.Property<decimal?>("PuntosLocal_Prorroga2")
                        .HasPrecision(5)
                        .HasColumnType("decimal(5,0)");

                    b.Property<decimal?>("PuntosVisitante_P1")
                        .HasPrecision(5)
                        .HasColumnType("decimal(5,0)");

                    b.Property<decimal?>("PuntosVisitante_P2")
                        .HasPrecision(5)
                        .HasColumnType("decimal(5,0)");

                    b.Property<decimal?>("PuntosVisitante_P3")
                        .HasPrecision(5)
                        .HasColumnType("decimal(5,0)");

                    b.Property<decimal?>("PuntosVisitante_P4")
                        .HasPrecision(5)
                        .HasColumnType("decimal(5,0)");

                    b.Property<decimal?>("PuntosVisitante_Prorroga")
                        .HasPrecision(5)
                        .HasColumnType("decimal(5,0)");

                    b.Property<decimal?>("PuntosVisitante_Prorroga2")
                        .HasPrecision(5)
                        .HasColumnType("decimal(5,0)");

                    b.Property<int>("Ronda")
                        .HasColumnType("int");

                    b.Property<Guid>("TorneoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UltimaFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("UltimaModificacionPor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaHora");

                    b.HasIndex("GanadorId");

                    b.HasIndex("TorneoId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.PartidoArbitro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArbitroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PartidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Rol")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UltimaFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("UltimaModificacionPor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArbitroId");

                    b.HasIndex("PartidoId");

                    b.ToTable("PartidoArbitros");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.PartidoEquipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsGanador")
                        .HasColumnType("bit");

                    b.Property<bool>("EsLocal")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PartidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UltimaFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("UltimaModificacionPor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("PartidoId", "EquipoId")
                        .IsUnique();

                    b.ToTable("PartidoEquipos");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime?>("UltimaFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("UltimaModificacionPor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Identificacion")
                        .IsUnique();

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.Torneo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Formato")
                        .HasColumnType("int");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UltimaFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("UltimaModificacionPor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Torneos");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.TorneoEquipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Posicion")
                        .HasColumnType("int");

                    b.Property<Guid>("TorneoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UltimaFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("UltimaModificacionPor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("TorneoId");

                    b.ToTable("TorneoEquipos");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.Arbitro", b =>
                {
                    b.HasOne("OrganizadorCampeonato.Dominio.Entidades.Persona", "Persona")
                        .WithOne("Arbitro")
                        .HasForeignKey("OrganizadorCampeonato.Dominio.Entidades.Arbitro", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.Entrenador", b =>
                {
                    b.HasOne("OrganizadorCampeonato.Dominio.Entidades.Persona", "Persona")
                        .WithOne("Entrenador")
                        .HasForeignKey("OrganizadorCampeonato.Dominio.Entidades.Entrenador", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.Equipo", b =>
                {
                    b.HasOne("OrganizadorCampeonato.Dominio.Entidades.Categoria", "Categoria")
                        .WithMany("Equipos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OrganizadorCampeonato.Dominio.Entidades.Entrenador", "Entrenador")
                        .WithMany("Equipos")
                        .HasForeignKey("EntrenadorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Categoria");

                    b.Navigation("Entrenador");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.EquipoJugador", b =>
                {
                    b.HasOne("OrganizadorCampeonato.Dominio.Entidades.Equipo", "Equipo")
                        .WithMany("EquipoJugadores")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OrganizadorCampeonato.Dominio.Entidades.Jugador", "Jugador")
                        .WithMany("EquipoJugadores")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Jugador");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.Jugador", b =>
                {
                    b.HasOne("OrganizadorCampeonato.Dominio.Entidades.Persona", "Persona")
                        .WithOne("Jugador")
                        .HasForeignKey("OrganizadorCampeonato.Dominio.Entidades.Jugador", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.Partido", b =>
                {
                    b.HasOne("OrganizadorCampeonato.Dominio.Entidades.Equipo", "Ganador")
                        .WithMany()
                        .HasForeignKey("GanadorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OrganizadorCampeonato.Dominio.Entidades.Torneo", "Torneo")
                        .WithMany("Partidos")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Ganador");

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.PartidoArbitro", b =>
                {
                    b.HasOne("OrganizadorCampeonato.Dominio.Entidades.Arbitro", "Arbitro")
                        .WithMany("PartidoArbitros")
                        .HasForeignKey("ArbitroId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OrganizadorCampeonato.Dominio.Entidades.Partido", "Partido")
                        .WithMany("PartidoArbitros")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Arbitro");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.PartidoEquipo", b =>
                {
                    b.HasOne("OrganizadorCampeonato.Dominio.Entidades.Equipo", "Equipo")
                        .WithMany("PartidoEquipos")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OrganizadorCampeonato.Dominio.Entidades.Partido", "Partido")
                        .WithMany("PartidoEquipos")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.Torneo", b =>
                {
                    b.HasOne("OrganizadorCampeonato.Dominio.Entidades.Categoria", "Categoria")
                        .WithMany("Torneos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.TorneoEquipo", b =>
                {
                    b.HasOne("OrganizadorCampeonato.Dominio.Entidades.Equipo", "Equipo")
                        .WithMany("TorneoEquipos")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OrganizadorCampeonato.Dominio.Entidades.Torneo", "Torneo")
                        .WithMany("TorneoEquipos")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.Arbitro", b =>
                {
                    b.Navigation("PartidoArbitros");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.Categoria", b =>
                {
                    b.Navigation("Equipos");

                    b.Navigation("Torneos");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.Entrenador", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.Equipo", b =>
                {
                    b.Navigation("EquipoJugadores");

                    b.Navigation("PartidoEquipos");

                    b.Navigation("TorneoEquipos");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.Jugador", b =>
                {
                    b.Navigation("EquipoJugadores");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.Partido", b =>
                {
                    b.Navigation("PartidoArbitros");

                    b.Navigation("PartidoEquipos");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.Persona", b =>
                {
                    b.Navigation("Arbitro");

                    b.Navigation("Entrenador");

                    b.Navigation("Jugador");
                });

            modelBuilder.Entity("OrganizadorCampeonato.Dominio.Entidades.Torneo", b =>
                {
                    b.Navigation("Partidos");

                    b.Navigation("TorneoEquipos");
                });
#pragma warning restore 612, 618
        }
    }
}
